### ISSUE TITLE
Trying to build up the experiment

### ISSUE THREAD

**Issue by JustinChiu1210** [jrayzhang6/CFR-RL#3]
![issue1](https://user-images.githubusercontent.com/41098446/154080511-e62d17b2-5333-4c36-918c-b040744352cb.PNG)
Hi Zhang, I'm a beginner in the RL and I'm trying to build up the experiment enviorment, but it came out the error messae of this, so I reach for your help, Thanks.

**Comment by jrayzhang6** [comment]
Hi Justin,

It seems like you are using only one cpu core. In that case, FLAGS.num_agents = 0. That is why the error comes up.

**Comment by JustinChiu1210** [comment]
Thanks for the reply, maybe I will set it to 1 and run.
